version: '3.8'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookstore
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U postgres -d bookstore -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated

  api:
    image: matheusvict/book-e-commerce:latest
    hostname: api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bookstore
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
    depends_on:
      db:
        condition: service_healthy



networks:
  default:
    driver: bridge
    name: bookstore