CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid             UUID                                    NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    author           VARCHAR(255)                            NOT NULL,
    publication_date TIMESTAMP WITHOUT TIME ZONE,
    stock            INTEGER                                 NOT NULL,
    category_id      BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_uuid UNIQUE (uuid);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);