CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   UUID                                    NOT NULL,
    book_id    BIGINT                                  NOT NULL,
    amount     INTEGER                                 NOT NULL,
    status     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_orderid UNIQUE (order_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);